paths:
  /api/product/:
  get:
  summary: Obtener todos los productos
  tags:
    - Products
  responses:
  '200':
    description: Productos obtenidos satisfactoriamente
  '500':
    description: Error interno del servidor al obtener los productos
